[project]
name = "idalindvall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cloudinary>=1.44.2",
    "fastapi[standard]>=0.136.1",
    "langchain>=1.2.17",
    "langchain-anthropic>=1.4.3",
    "openpyxl>=3.1.5",
]
